### ISSUE TITLE
Help with code review for Chap6

### ISSUE THREAD

**Issue by AzraFlow** [AzraFlow/PythonAutomate#28]
Please fix any pep8 issues you find also.

**Comment by mbuhidar** [comment]
I'll work on this.

**Comment by AzraFlow** [comment]
OK, thanks @mbuhidar.

**Comment by mbuhidar** [comment]
In the bulletPointAdder.py file, the pyperclip module doesn't appear to support Linux - gives the following error:  
'Pyperclip could not find a copy/paste mechanism for your system.  For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error'

I know this worked for Windows, so I will not change the code at all for now. 
Will look at the others though.

**Comment by mbuhidar** [comment]
Added alternate pattern for if/else sequence to pigLat.py.  I left the original expanded form as commented code for reference and education.
